---
title: "Data Wrangling NPAT intensity"
author: "Jacob Roth"
date: "2025-06-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Libraries}

# Load necessary libraries
library(readr)
library(fs)
library(stringr)
library(purrr)
library(dplyr)
library(ggplot2)
library(readxl)
library(lubridate)

date2 <- ymd(today())
date <- format(ymd(today()), "%Y%m%d")

```


```{r Get timecourse PRMTi data}
getwd()
#Collect all files in my wd folder that end in "Top100Codependencies_CRISPR.csv$" or "Top100Codependencies_RNAi.csv$" and make a list of said files
#$ at the end indicates the end of the text of interest

# CBCount_list <- list.files(pattern = "CoilinCountPerNucleus_Macro-.*.csv$", 
#                         recursive = TRUE)
NPATCount_list <- list.files(pattern = "Quantification_puncta-NPAT.csv$", 
                        recursive = TRUE)

#Read all files in "file_list"
##review lapply here: https://www.earthdatascience.org/courses/earth-analytics/automate-science-workflows/use-apply-functions-for-efficient-code-r/
data_NPATCount <- lapply(NPATCount_list, function(x){
  read.csv(x, 
             header = TRUE, 
             sep = ",", 
             stringsAsFactors = FALSE)})

names(data_NPATCount) <- NPATCount_list


# Rename dataframes and add new column for file path
# add new column
data_NPATCount <- lapply(names(data_NPATCount), function(old_name) {
  # Get the dataframe from the list
  df <- data_NPATCount[[old_name]]
  
  # Add a new column with the old name
  df$FilePath <- old_name
  
  # Return the modified dataframe
  return(df)
})


# #shorten name of each file to only reference the parent dataset
# CBCount_files <- gsub("4-data_processed/20231220_Batch05/", "", CBCount_list)
# CBCount_files <- gsub("4-data_processed/20231221_Batch05/", "", CBCount_files)
# # CBCount_files <- gsub("/CoilinCountPerNucleus_Macro-.*.csv", "", CBCount_files)
NPATCount_files <- gsub("/NPAT-Measure/Quantification_puncta-NPAT.csv", "", NPATCount_list)

# NPATCount_files <- gsub("_Stitch_01/NPAT-Measure/Quantification_puncta-NPAT.csv", "", NPATCount_files)

names(data_NPATCount) <- NPATCount_files


```

# Merge datasets

```{r create df}
df_NPATCount <- bind_rows(data_NPATCount,
                  .id = "folder")

# df_NPATCount$macro <- str_extract(data_NPATCount$FilePath, "Macro-[^.]*")

# This code will extract the substring that starts with "Macro-" and continues until it encounters a forward slash (/) or #the end of the string, whichever comes first. The extracted substring is then stored in a new column named 'macro'.

#pivot
#remove pval 
# colnames(DESEQ2_df)
# df_NPATCount <- dplyr::select(df_NPATCount,
# c("folder","Nucleus", "Nucleus.Size","NPAT.Count","FilePath"))
```

```{r}

library(dplyr)

df_NPATCount <- df_NPATCount %>%
  mutate(slide = substr(folder, 1, 7))

# Define the reference mapping
alignment_df <- data.frame(
  slide    = c("JSRs092", "JSRs093", "JSRs094", "JSRs095", "JSRs096", "JSRs097"),
  Treatment2 = c("p033-DMSO",    "p033-GSK591",  "p108-DMSO",    "p108-GSK591",  "p110-DMSO",    "p110-GSK591"),
  Treatment = c("DMSO",    "pGSK591",  "DMSO",    "GSK591",  "DMSO",    "GSK591"),
  Duration  = c(96,        96,        96,        96,        96,         96)
)

# Add 'folder' column to df_NPATCount based on Slide name
df_NPATCount <- df_NPATCount %>%
  # mutate(folder = stringr::str_extract(Slide, "JSRs\\d+")) %>%  # Extract folder name
  left_join(alignment_df, by = "slide")  # Add Treatment and Duration

df_NPATCount$TreatmentDuration <- paste(df_NPATCount$Treatment,df_NPATCount$Duration,
                                        sep ="-")

library(dplyr)

df_NPATCount <- df_NPATCount %>%
  mutate(Color = if_else(Treatment == "DMSO", "#D4D4D4", "#0F8745"))

library(dplyr)
library(dplyr)

df_NPATCount <- df_NPATCount %>%
  mutate(Treated = if_else(grepl("DMSO", TreatmentDuration), "DMSO", TreatmentDuration))



```





```{r NPAT puncta Intensity stat, eval = TRUE}

# plotme = c("H4-wt", "H4R3K","H4R3A" ,"H4R3C")

# Define the output path
# output_dir <- paste("/Users/jacobroth/Library/CloudStorage/OneDrive-Personal/RothJacob_PhDFiles/1-Projects/2-Experiments/JSRe0278-T_Cellular_NB06-000_OverExpressionOfMutantH4-Lentiviral/5-figures/20240610_Batch02",sep = "")

# Load required package
library(ggpubr)

# label_mapping <- c("NT","1","2")

# Create the plot
plot <- df_NPATCount %>%
  # filter(Treatment %in% plotme) %>%
  ggplot(aes(x = fct_relevel(Treatment2, 
                             "p033-DMSO",    "p033-GSK591",  "p108-DMSO",    "p108-GSK591",  "p110-DMSO",    "p110-GSK591"),
             y = Mean, color = Treatment)) +
  # Data visualization
  geom_violin(aes(fill = Treatment),
              # alpha = 0.4, 
              scale = "width", width = 0.6) +  # Violin plot
  geom_boxplot(aes(fill = Treatment),
               width = 0.15, 
               # alpha = 0.6,
               outlier.shape = NA, color = "black") +  # Boxplot
  # geom_jitter(position = position_jitter(width = 0.15), size = 1, alpha = 0.7) +  # Jittered points
  
  # Custom colors
  scale_color_manual(values = setNames(df_NPATCount$Color, df_NPATCount$Treatment)) +
  scale_fill_manual(values = setNames(df_NPATCount$Color, df_NPATCount$Treatment)) +
  
  # Labels and theme
  labs(
    title = "NPAT Intensity",
    # subtitle = "Palbociclib-released A549 cells",
    x = "Treatment",
    y = "NPAT Intensity (RFU)",
    fill = "Treatment"
  ) +
  # Theme adjustments
      # scale_x_discrete(labels = label_mapping) +  # Change x-axis labels to DurationHr
  theme_minimal(base_size = 14) +
  # theme(
  #   # axis.text.x = element_text(size = 24,
  #   #                            angle = 45, hjust = 1, vjust = 1,
  #   #                            color = "black", face = "plain"),
  #   axis.text.x  = element_blank(),
  #   axis.text.y = element_text(size = 24,color = "black", face = "plain"),
  #   axis.title = element_text(size = 24, face = "plain"),
  #   # axis.title.x  = element_blank(),
  #   legend.position = "none",
  #   panel.grid.major = element_blank(),  # Remove major gridlines
  #   panel.grid.minor = element_blank(),  # Remove minor gridlines
  #   panel.border = element_blank(),      # Remove border around plot
  #   axis.line = element_line(color = "black", size = 1.2),  # Keep only X and Y axes
  #   legend.text = element_text(color = "black", face = "plain"),  # Change legend text
  #   legend.title = element_text(color = "black", face = "plain"),  # Change legend title
  #   plot.title = element_text(size = 24,color = "black", face = "plain"),  # Change plot title
  #   plot.subtitle = element_text(color = "black", face = "plain"),  # Change subtitle
  #   text = element_text(color = "black", face = "plain"),  # Set all text to black and regular
  # )+
  theme(
  # axis.text.x = element_text(size = 24,
  #                            angle = 45, hjust = 1, vjust = 1,
  #                            color = "black", face = "plain"),
  axis.text.x  = element_blank(),
  axis.text.y = element_text(size = 24, color = "black", face = "plain"),
  axis.title = element_text(size = 24, face = "plain"),
  # axis.title.x  = element_blank(),
  legend.position = "none",
  panel.grid.major = element_blank(),   # Remove major gridlines
  panel.grid.minor = element_blank(),   # Remove minor gridlines
  panel.border = element_blank(),       # Remove border around plot
  axis.line = element_line(color = "black", size = 0.4),  # ⬅️ Thinner axis lines
  legend.text = element_text(color = "black", face = "plain"),
  legend.title = element_text(color = "black", face = "plain"),
  plot.title = element_text(size = 24, color = "black", face = "plain"),
  plot.subtitle = element_text(color = "black", face = "plain"),
  text = element_text(color = "black", face = "plain")
)+
  ylim(0,130)+
  # Statistical comparisons
    # scale_x_discrete(labels = label_mapping) +  # Change x-axis labels to DurationHr
 stat_compare_means(
    method = "t.test",
    comparisons = list(
      c("p033-DMSO", "p033-GSK591"),
      c("p108-DMSO", "p108-GSK591"),
      c("p110-DMSO", "p110-GSK591")
    ),
    label = "p.signif",
    bracket.size = 0.75,
    tip.length = 0,
    label.y = c(120,120,120),  # Adjusts annotation height
    # label.y = c(700, 750, 800, 850,700),  # Adjusts annotation height
    size = 8, #default size is 5
    vjust = -0.1
  )

# Print the plot
plot

output_dir <- getwd()

# Define the filename
output_file <- file.path(output_dir, paste0("5-figures/NPAT-Puncta_Intensity-Violin-AllData-Stats2_", date, ".png"))
# Save the plot as a PNG
ggsave(filename = output_file, plot = plot, width = 6, height = 6, dpi = 300)


# Define PDF output filename
output_file_pdf <- file.path(output_dir, paste0("5-figures/NPAT-Puncta_Intensity-Violin-AllData-Stats2_", date, ".pdf"))

# Save the plot as a PDF
ggsave(filename = output_file_pdf, plot = plot, width = 6, height = 6, useDingbats = FALSE)

```
```{r NPAT puncta Area stat, eval = TRUE}

# plotme = c("H4-wt", "H4R3K","H4R3A" ,"H4R3C")

# Define the output path
# output_dir <- paste("/Users/jacobroth/Library/CloudStorage/OneDrive-Personal/RothJacob_PhDFiles/1-Projects/2-Experiments/JSRe0278-T_Cellular_NB06-000_OverExpressionOfMutantH4-Lentiviral/5-figures/20240610_Batch02",sep = "")

# Load required package
library(ggpubr)

# label_mapping <- c("NT","1","2")

# Create the plot
plot <- df_NPATCount %>%
  # filter(Treatment %in% plotme) %>%
  ggplot(aes(x = fct_relevel(Treatment2, 
                             "p033-DMSO",    "p033-GSK591",  "p108-DMSO",    "p108-GSK591",  "p110-DMSO",    "p110-GSK591"),
             y = Area, color = Treatment)) +
  # Data visualization
  geom_violin(aes(fill = Treatment),
              # alpha = 0.4, 
              scale = "width", width = 0.6) +  # Violin plot
  geom_boxplot(aes(fill = Treatment),
               width = 0.15, 
               # alpha = 0.6,
               outlier.shape = NA, color = "black") +  # Boxplot
  # geom_jitter(position = position_jitter(width = 0.15), size = 1, alpha = 0.7) +  # Jittered points
  
  # Custom colors
  scale_color_manual(values = setNames(df_NPATCount$Color, df_NPATCount$Treatment)) +
  scale_fill_manual(values = setNames(df_NPATCount$Color, df_NPATCount$Treatment)) +
  
  # Labels and theme
 labs(
    title = "NPAT Area",
    # subtitle = "Palbociclib-released A549 cells",
    x = "Treatment",
    y = expression("NPAT Area (" * mu * "m"^2 * ")"),
    fill = "Treatment"
  ) +
  # Theme adjustments
      # scale_x_discrete(labels = label_mapping) +  # Change x-axis labels to DurationHr
  theme_minimal(base_size = 14) +
  theme(
  # axis.text.x = element_text(size = 24,
  #                            angle = 45, hjust = 1, vjust = 1,
  #                            color = "black", face = "plain"),
  axis.text.x  = element_blank(),
  axis.text.y = element_text(size = 24, color = "black", face = "plain"),
  axis.title = element_text(size = 24, face = "plain"),
  # axis.title.x  = element_blank(),
  legend.position = "none",
  panel.grid.major = element_blank(),   # Remove major gridlines
  panel.grid.minor = element_blank(),   # Remove minor gridlines
  panel.border = element_blank(),       # Remove border around plot
  axis.line = element_line(color = "black", size = 0.4),  # ⬅️ Thinner axis lines
  legend.text = element_text(color = "black", face = "plain"),
  legend.title = element_text(color = "black", face = "plain"),
  plot.title = element_text(size = 24, color = "black", face = "plain"),
  plot.subtitle = element_text(color = "black", face = "plain"),
  text = element_text(color = "black", face = "plain")
)+
  ylim(0,3)+
  # Statistical comparisons
    # scale_x_discrete(labels = label_mapping) +  # Change x-axis labels to DurationHr
  stat_compare_means(
    method = "t.test",
    comparisons = list(
      c("p033-DMSO", "p033-GSK591"),
      c("p108-DMSO", "p108-GSK591"),
      c("p110-DMSO", "p110-GSK591")
    ),
    label = "p.signif",
    bracket.size = 0.75,
    tip.length = 0,
    label.y = c(2.25,2.25,2.25),  # Adjusts annotation height
    # label.y = c(700, 750, 800, 850,700),  # Adjusts annotation height
    size = 8, #default size is 5
    vjust = -0.1
  )

# Print the plot
plot

output_dir <- getwd()

# Define the filename
output_file <- file.path(output_dir, paste0("5-figures/NPAT-Puncta_Area-Violin-AllData-Stats_", date, ".png"))
# Save the plot as a PNG
ggsave(filename = output_file, plot = plot, width = 6, height = 6, dpi = 300)


# Define PDF output filename
output_file_pdf <- file.path(output_dir, paste0("5-figures/NPAT-Puncta_Area-Violin-AllData-Stats_", date, ".pdf"))

# Save the plot as a PDF
ggsave(filename = output_file_pdf, plot = plot, width = 6, height = 6, useDingbats = FALSE)

```





```{r NPAT puncta area stat, eval = TRUE}

plotme = c("H4-wt", "H4R3K","H4R3A" ,"H4R3C")

# Define the output path
output_dir <- paste("/Users/jacobroth/Library/CloudStorage/OneDrive-Personal/RothJacob_PhDFiles/1-Projects/2-Experiments/JSRe0278-T_Cellular_NB06-000_OverExpressionOfMutantH4-Lentiviral/5-figures/20240610_Batch02",sep = "")

library(ggpubr)

# label_mapping <- c("NT","1","2")

# Create the plot
plot <- data_NPATmeasure %>%
  filter(Treatment %in% plotme) %>%
  ggplot(aes(x = fct_relevel(Treatment, "H4-wt", "H4R3K","H4R3A" ,"H4R3C"),
             y = Area, color = Treatment)) +
  # Data visualization
  geom_violin(aes(fill = Treatment),
              # alpha = 0.4, 
              scale = "width", width = 0.6) +  # Violin plot
  geom_boxplot(aes(fill = Treatment),
               width = 0.15, 
               # alpha = 0.6,
               outlier.shape = NA, color = "black") +  # Boxplot
  # geom_jitter(position = position_jitter(width = 0.15), size = 1, alpha = 0.7) +  # Jittered points
  
  # Custom colors
  scale_color_manual(values = setNames(data_NPATmeasure$Color, data_NPATmeasure$Treatment)) +
  scale_fill_manual(values = setNames(data_NPATmeasure$Color, data_NPATmeasure$Treatment)) +
  
  # Labels and theme
  labs(
    title = "NPAT Area",
    # subtitle = "Palbociclib-released A549 cells",
    x = "Treatment",
    y = expression("NPAT Area (" * mu * "m"^2 * ")"),
    fill = "Treatment"
  ) +
  # Theme adjustments
      # scale_x_discrete(labels = label_mapping) +  # Change x-axis labels to DurationHr
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(size = 24,
                               angle = 45, hjust = 1, vjust = 1,
                               color = "black", face = "plain"),
    # axis.text.x  = element_blank(),
    axis.text.y = element_text(size = 24,color = "black", face = "plain"),
    axis.title = element_text(size = 24, face = "plain"),
    # axis.title.x  = element_blank(),
    legend.position = "none",
    panel.grid.major = element_blank(),  # Remove major gridlines
    panel.grid.minor = element_blank(),  # Remove minor gridlines
    panel.border = element_blank(),      # Remove border around plot
    axis.line = element_line(color = "black", size = 1.2),  # Keep only X and Y axes
    legend.text = element_text(color = "black", face = "plain"),  # Change legend text
    legend.title = element_text(color = "black", face = "plain"),  # Change legend title
    plot.title = element_text(size = 24,color = "black", face = "plain"),  # Change plot title
    plot.subtitle = element_text(color = "black", face = "plain"),  # Change subtitle
    text = element_text(color = "black", face = "plain"),  # Set all text to black and regular
  )+
  ylim(0,2.5)+
  # Statistical comparisons
    # scale_x_discrete(labels = label_mapping) +  # Change x-axis labels to DurationHr
  stat_compare_means(
    method = "t.test",
    comparisons = list(
      # c("GFP", "H4-wt"),
      c("H4-wt", "H4R3K"),
      c("H4-wt", "H4R3A"),
      c("H4-wt", "H4R3C")
    ),
    label = "p.signif",
    bracket.size = 0.75,
    tip.length = 0,
    label.y = c(1.3,1.5, 1.7),  # Adjusts annotation height
    # label.y = c(700, 750, 800, 850,700),  # Adjusts annotation height
    size = 8, #default size is 5
    vjust = -0.1
  )

# Print the plot
plot


# Define the filename
output_file <- file.path(output_dir, paste0("NPAT-Puncta_Area-Violin-AllData-Stats_", date, ".png"))
# Load required package

# Save the plot as a PNG
ggsave(filename = output_file, plot = plot, width = 6, height = 6, dpi = 300)


# Define PDF output filename
output_file_pdf <- file.path(output_dir, paste0("NPAT-Puncta_Area-Violin-AllData-stats_", date, ".pdf"))

# Save the plot as a PDF
ggsave(filename = output_file_pdf, plot = plot, width = 6, height = 6, useDingbats = FALSE)

# Print the path of the saved file
# message("Plot saved to: ", output_file)
```

findme
```{r H4 at NPAT puncta Intensity stat, eval = TRUE}

# plotme = c("JSRs098","JSRs100","JSRs102")

# Define the output path
output_dir <- paste("/Users/jacobroth/Library/CloudStorage/OneDrive-Personal/RothJacob_PhDFiles/1-Projects/2-Experiments/JSRe0278-T_Cellular_NB06-000_OverExpressionOfMutantH4-Lentiviral/5-figures/20240610_Batch02",sep = "")

# Define the filename
# output_file <- file.path(output_dir, paste0("H4-AtNPAT-Puncta_Intensity-Violin-AllData-Stat-Tall_", date, ".png"))
output_file <- file.path(output_dir, paste0("H4-AtNPAT-Puncta_Intensity-Violin-AllData-NoStat_", date, ".png"))
# Load required package
library(ggpubr)

# label_mapping <- c("NT","1","2")

# Create the plot
plot <- data_NPATwithH4 %>%
  # filter(Slide %in% plotme) %>%
  ggplot(aes(x = fct_relevel(Treatment, "GFP", "H4-wt", "H4R3K","H4R3A" ,"H4R3C"),
             y = Mean_H4, color = Treatment)) +
  # Data visualization
  geom_violin(aes(fill = Treatment),
              # alpha = 0.4, 
              scale = "width", width = 0.6) +  # Violin plot
  geom_boxplot(aes(fill = Treatment),
               width = 0.15, 
               # alpha = 0.6,
               outlier.shape = NA, color = "black") +  # Boxplot
  # geom_jitter(position = position_jitter(width = 0.15), size = 1, alpha = 0.7) +  # Jittered points
  
  # Custom colors
  scale_color_manual(values = setNames(data_NPATmeasure$Color, data_NPATmeasure$Treatment)) +
  scale_fill_manual(values = setNames(data_NPATmeasure$Color, data_NPATmeasure$Treatment)) +
  
  # Labels and theme
  labs(
    # title = "H4 Intensity",
    # subtitle = "Palbociclib-released A549 cells",
    x = "Treatment",
    y = "H4 Intensity at NPAT (RFU)",
    # fill = "Treatment"
  ) +
  # Theme adjustments
      # scale_x_discrete(labels = label_mapping) +  # Change x-axis labels to DurationHr
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(size = 24,
                               angle = 45, hjust = 1, vjust = 1,
                               color = "black", face = "plain"),
    # axis.text.x  = element_blank(),
    axis.text.y = element_text(size = 24,color = "black", face = "plain"),
    axis.title = element_text(size = 24, face = "plain"),
    # axis.title.x  = element_blank(),
    legend.position = "none",
    panel.grid.major = element_blank(),  # Remove major gridlines
    panel.grid.minor = element_blank(),  # Remove minor gridlines
    panel.border = element_blank(),      # Remove border around plot
    axis.line = element_line(color = "black", size = 1.2),  # Keep only X and Y axes
    legend.text = element_text(color = "black", face = "plain"),  # Change legend text
    legend.title = element_text(color = "black", face = "plain"),  # Change legend title
    plot.title = element_text(size = 24,color = "black", face = "plain"),  # Change plot title
    plot.subtitle = element_text(color = "black", face = "plain"),  # Change subtitle
    text = element_text(color = "black", face = "plain"),  # Set all text to black and regular
  )+
  ylim(-1,300)
  # ylim(-1,375)+
  # # Statistical comparisons
  #   # scale_x_discrete(labels = label_mapping) +  # Change x-axis labels to DurationHr
  # stat_compare_means(
  #   method = "t.test",
  #   comparisons = list(
  #     c("H4-wt", "H4R3K"),
  #     c("H4-wt", "H4R3A"),
  #     c("H4-wt", "H4R3C")
  #   ),
  #   label = "p.signif",
  #   bracket.size = 0.75,
  #   tip.length = 0,
  #   # label.y = c(1.3,1.5, 1.7, 1.9),  # Adjusts annotation height
  #   label.y = c(250, 300, 350),  # Adjusts annotation height
  #   size = 8, #default size is 5
  #   vjust = -0.1
  # )

# Print the plot
plot


# Save the plot as a PNG
ggsave(filename = output_file, plot = plot, width = 6, height = 6, dpi = 300)

# Define PDF output filename
output_file_pdf <- file.path(output_dir, paste0("H4-AtNPAT-Puncta_Intensity-Violin-AllData-NoStat_", date, ".pdf"))

# Save the plot as a PDF
ggsave(filename = output_file_pdf, plot = plot, width = 6, height = 6, useDingbats = FALSE)



# Print the path of the saved file
# message("Plot saved to: ", output_file)
```

```{r Nuclei area stat, eval = TRUE}

# plotme = c("JSRs098","JSRs100","JSRs102")

# Define the output path
output_dir <- paste("/Users/jacobroth/Library/CloudStorage/OneDrive-Personal/RothJacob_PhDFiles/1-Projects/2-Experiments/JSRe0278-T_Cellular_NB06-000_OverExpressionOfMutantH4-Lentiviral/5-figures/20240610_Batch02",sep = "")

# Define the filename
output_file <- file.path(output_dir, paste0("Nucleus_Area-Violin-AllData-Stat_", date, ".png"))
# Load required package
library(ggpubr)

# label_mapping <- c("NT","1","2")

# Create the plot
plot <- data_Nuclei %>%
  # filter(Slide %in% plotme) %>%
  ggplot(aes(x = fct_relevel(Treatment, "GFP", "H4-wt", "H4R3A","H4R3K" ,"H4R3C"),
             y = Area, color = Treatment)) +
  # Data visualization
  geom_violin(aes(fill = Treatment),
              # alpha = 0.4, 
              scale = "width", width = 0.6) +  # Violin plot
  geom_boxplot(aes(fill = Treatment),
               width = 0.15, 
               # alpha = 0.6,
               outlier.shape = NA, color = "black") +  # Boxplot
  # geom_jitter(position = position_jitter(width = 0.15), size = 1, alpha = 0.7) +  # Jittered points
  
  # Custom colors
  scale_color_manual(values = setNames(data_NPATmeasure$Color, data_NPATmeasure$Treatment)) +
  scale_fill_manual(values = setNames(data_NPATmeasure$Color, data_NPATmeasure$Treatment)) +
  
  # Labels and theme
  labs(
    title = "Nuclear Area",
    # subtitle = "Palbociclib-released A549 cells",
    x = "Treatment",
    y = expression("Nucleus Area (" * mu * "m"^2 * ")"),
    fill = "Treatment"
  ) +
  # Theme adjustments
      # scale_x_discrete(labels = label_mapping) +  # Change x-axis labels to DurationHr
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(size = 24,
                               angle = 45, hjust = 1, vjust = 1,
                               color = "black", face = "plain"),
    # axis.text.x  = element_blank(),
    axis.text.y = element_text(size = 24,color = "black", face = "plain"),
    axis.title = element_text(size = 24, face = "plain"),
    # axis.title.x  = element_blank(),
    legend.position = "none",
    panel.grid.major = element_blank(),  # Remove major gridlines
    panel.grid.minor = element_blank(),  # Remove minor gridlines
    panel.border = element_blank(),      # Remove border around plot
    axis.line = element_line(color = "black", size = 1.2),  # Keep only X and Y axes
    legend.text = element_text(color = "black", face = "plain"),  # Change legend text
    legend.title = element_text(color = "black", face = "plain"),  # Change legend title
    plot.title = element_text(size = 24,color = "black", face = "plain"),  # Change plot title
    plot.subtitle = element_text(color = "black", face = "plain"),  # Change subtitle
    text = element_text(color = "black", face = "plain"),  # Set all text to black and regular
  )+
  ylim(0,800)+
  # Statistical comparisons
  # scale_x_discrete(labels = label_mapping) +  # Change x-axis labels to DurationHr
  stat_compare_means(
    method = "t.test",
    comparisons = list(
      c("GFP", "H4-wt"),
      c("GFP", "H4R3A"),
      c("GFP", "H4R3K"),
      c("GFP", "H4R3C")
    ),
    label = "p.signif",
    bracket.size = 0.75,
    tip.length = 0,
    # label.y = c(1.3,1.5, 1.7, 1.9),  # Adjusts annotation height
    label.y = c(550, 600, 650, 700),  # Adjusts annotation height
    size = 8, #default size is 5
    vjust = -0.1
  )

# Print the plot
plot


# Save the plot as a PNG
ggsave(filename = output_file, plot = plot, width = 6, height = 6, dpi = 300)

# Print the path of the saved file
# message("Plot saved to: ", output_file)
```